db_file: "bot.db"

bot_url: "https://t.me/pocket_list_bot"

messages:
  response:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала, тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизирован. Присылай ссылку, я ее сохраню"
    saved_successfully: "Ссылка успешно сохранена!"
    unknown_command: "Я не знаю такой команды :("
  error:
    default: "Произошла неизвестная ошибка"
    invalid_url: "Это невалидная ссылка!"
    unauthorized: "Ты не авторизирован! Используй команду /start!"
    unable_to_save: "Увы, не удалось сохранить ссылку. Попробуй еще раз позже."
